# Generated by Django 5.0 on 2024-01-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_otp_code_profile_otp_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
