# Generated by Django 5.0 on 2024-02-01 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_cartitem_edition_variant'),
        ('products', '0025_alter_product_edition_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='language_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_variant', to='products.languagevariant'),
        ),
    ]
