# Generated by Django 5.0 on 2024-02-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charge',
            field=models.IntegerField(blank=True, default=59, null=True),
        ),
    ]
