# Generated by Django 5.0 on 2024-02-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cart_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='refund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
