# Generated by Django 5.0 on 2024-01-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone_number',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(default='something', max_length=500),
        ),
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='New name', max_length=200),
        ),
    ]
