# Generated by Django 5.0 on 2024-02-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_is_active_orderitem_is_delivered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_variant',
            new_name='edition_variant',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='language_variant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
