# Generated by Django 5.0 on 2024-02-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_orderitem_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
