# Generated by Django 5.0 on 2024-01-03 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='products.category'),
        ),
    ]
