# Generated by Django 5.0 on 2024-01-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_subcategory_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
