# Generated by Django 5.0 on 2024-01-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_subcategory_order_alter_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
