# Generated by Django 5.0 on 2024-01-05 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_order_productimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(default='Write something'),
        ),
    ]
