# Generated by Django 5.0 on 2024-01-08 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_audiobook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebook_file', models.FileField(upload_to='ebooks')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ebook', to='products.product')),
            ],
        ),
    ]
