# Generated by Django 5.0 on 2024-01-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_category_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_category_listed',
            field=models.BooleanField(default=True),
        ),
    ]
