# Generated by Django 5.0 on 2024-01-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_editionvariant_languagevariant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editionvariant',
            old_name='edition_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='languagevariant',
            old_name='language_name',
            new_name='name',
        ),
    ]
