# Generated by Django 5.0 on 2024-01-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_rename_edition_name_editionvariant_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='edition_variant',
            field=models.ManyToManyField(blank=True, to='products.editionvariant'),
        ),
        migrations.AlterField(
            model_name='product',
            name='language_variant',
            field=models.ManyToManyField(blank=True, to='products.languagevariant'),
        ),
    ]
