# Generated by Django 5.0 on 2024-02-08 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 12, 13, 2, 526166, tzinfo=datetime.timezone.utc)),
        ),
    ]
