# Generated by Django 5.0 on 2024-02-08 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_cart_coupon'),
        ('products', '0028_coupon_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='carts_used',
            field=models.ManyToManyField(blank=True, related_name='used_coupons', to='accounts.cart'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 13, 31, 57, 43331, tzinfo=datetime.timezone.utc)),
        ),
    ]
