# Generated by Django 5.0 on 2024-02-08 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_coupon_carts_used_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 9, 13, 55, 32, 24087, tzinfo=datetime.timezone.utc)),
        ),
    ]
