# Generated by Django 5.0 on 2024-02-08 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 13, 56, 20, 384949, tzinfo=datetime.timezone.utc)),
        ),
    ]
