# Generated by Django 5.0 on 2024-02-17 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0037_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 12, 33, 19, 472551, tzinfo=datetime.timezone.utc)),
        ),
    ]
