# Generated by Django 5.0 on 2024-02-19 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0039_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 19, 9, 18, 36, 264288, tzinfo=datetime.timezone.utc)),
        ),
    ]
