# Generated by Django 5.0 on 2024-02-22 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 4, 38, 21, 458049, tzinfo=datetime.timezone.utc)),
        ),
    ]
