# Generated by Django 5.0 on 2024-02-24 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0043_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 9, 7, 55, 728987, tzinfo=datetime.timezone.utc)),
        ),
    ]
