# Generated by Django 5.0 on 2024-02-27 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0045_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 11, 57, 2, 553086, tzinfo=datetime.timezone.utc)),
        ),
    ]
