# Generated by Django 5.0 on 2024-02-27 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 17, 11, 0, 644051, tzinfo=datetime.timezone.utc)),
        ),
    ]
