# Generated by Django 5.0 on 2024-03-15 01:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionvariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='languagevariant',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 1, 58, 36, 339212, tzinfo=datetime.timezone.utc)),
        ),
    ]
