# Generated by Django 5.0 on 2024-03-12 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0047_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 6, 53, 50, 879919, tzinfo=datetime.timezone.utc)),
        ),
    ]
