# Generated by Django 5.0 on 2024-03-12 07:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0048_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 7, 26, 58, 183231, tzinfo=datetime.timezone.utc)),
        ),
    ]
