# Generated by Django 5.0 on 2024-03-16 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_alter_coupon_expiration_date_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editionvariant',
            name='stock_quantity',
        ),
        migrations.RemoveField(
            model_name='languagevariant',
            name='stock_quantity',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 16, 4, 36, 1, 576075, tzinfo=datetime.timezone.utc)),
        ),
    ]
