# Generated by Django 5.0 on 2024-03-15 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_alter_coupon_expiration_date_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 13, 44, 22, 704368, tzinfo=datetime.timezone.utc)),
        ),
    ]
