<<<<<<< HEAD
# Generated by Django 5.0 on 2024-03-15 13:44
=======
# Generated by Django 5.0 on 2024-03-12 07:30
>>>>>>> 3fb4147 (online change)

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('products', '0049_alter_coupon_expiration_date_productvariant'),
=======
        ('products', '0049_alter_coupon_expiration_date'),
>>>>>>> 3fb4147 (online change)
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 13, 44, 22, 704368, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 12, 7, 30, 18, 479929, tzinfo=datetime.timezone.utc)),
>>>>>>> 3fb4147 (online change)
        ),
    ]
