# Generated by Django 5.0 on 2025-03-21 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0051_alter_coupon_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 21, 8, 35, 19, 364489, tzinfo=datetime.timezone.utc)),
        ),
    ]
